name: Drink Water

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Content-Type: application/json" \
               -d '{"content":"drink water"}' \
               "$DISCORD_WEBHOOK_URL"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
